---
- name: Play Web - Create apache directories and username in web servers
  hosts: dev
  become: yes
  become_user: ansible
  ansible_user: ansible
  ansible_connection: ssh
  ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
