---
- name: Play Web - Create apache directories and username in web servers
  hosts: dev
  become_user: root

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: installed
